### ISSUE TITLE
How can I added more pages?

### ISSUE THREAD

**Issue by ifsheldon** [ashutosh1919/masterPortfolio#122]
I am completely new to React, but when I tried to modify your code, I kinda understand the architecture. But, what places I need to add more code in order to add a new page? say, I'd like to have a page "Interest" that details my hobbies etc.

**Comment by sahilg50** [comment]
![image](https://user-images.githubusercontent.com/56653026/119515294-5e028e00-bd93-11eb-81e1-02fc23d1fc95.png)

As you can see that in the **main.js** there are different routes for different pages of the website, there you can add a route for your page too. You can continue to work on your page. Now the last step is to show the page name on the header. 

![image](https://user-images.githubusercontent.com/56653026/119515944-ed0fa600-bd93-11eb-9152-4c1c9be424cc.png)

You can add the page link and page name In the header by adding the Navlink in the **header.js**

**Comment by gabrieloliveirasobrinho** [comment]
I want this page to be exactly like contact page, how can I do it?

**Comment by saiteja13427** [comment]
@gabrieloliveirasobrinho Follow these steps 

1. Just copy the contact folder content under src/pages.
2. Make a new folder.
3. Paste the copied contents into this new folder.
4. Create a new route and navlink as mentioned by sahilg50.
5. And you will be good to go.

Please raise a new issue if you still have a problem.

Closing this for now, due to inactivity.
