### ISSUE TITLE
SVG copying as text

### ISSUE THREAD

**Issue by rahul-0000-code** [ashutosh1919/masterPortfolio#269]
When we try to put the svg image into code form and paste it into feeling proud.js it wont give a perfect matching since it shows an error as opacity and other errors

**Comment by ashutosh1919** [comment]
@rahul-0000-code please past the screenshot of the error and output.

**Comment by rahul-0000-code** [comment]
Also plz can you create a detailed video on how to create that logo illustrator because how much have forked and cloned your project, none of them have understood the process so they haven't included in their portfolio the illustration logo

**Comment by rahul-0000-code** [comment]
<img width="956" alt="1" src="https://user-images.githubusercontent.com/85439546/209446241-7ac21b50-ca74-4df3-8283-fe42f9fcebb5.PNG">
//These one was created with the description link provided by you in last video


<img width="960" alt="2" src="https://user-images.githubusercontent.com/85439546/209446253-fc3660f5-0d81-4210-97bc-0b6b7cdcda4d.PNG">
//These one was also created with the description link provided by you in last video


<img width="960" alt="3" src="https://user-images.githubusercontent.com/85439546/209446260-1b850d49-c147-40a2-b1ec-eea1624f7288.PNG">
//These one was created with the third video as per tutorial

**Comment by ashutosh1919** [comment]
@rahul-0000-code what is the exact problem you are facing? Can you please explain in detail?

**Comment by rahul-0000-code** [comment]
It has sorted now only issue is with the logo that is unique and everyone is facing that one

**Comment by ashutosh1919** [comment]
@rahul-0000-code what logo are you talking about? Can you please describe the problem in detail? Can you paste the screenshot of the logo which you are specifying?

**Comment by rahul-0000-code** [comment]
The figma illustration logo that appears when we open the website

**Comment by ashutosh1919** [comment]
@rahul-0000-code I have specifically mentioned in the YouTube playlist that the splash screen logo is currently not customisable since you will need to design your own logo. But I have created a [YouTube video](https://www.youtube.com/watch?v=SVxuydoSFwk) a while back to create such animated logo. You can follow it to create your own. 

We have currently no plan to make the splash screen logo customizable. But the `src/portfolio.js` file has option to remove splash screen if you don't have your own logo. Closing this issue.
